package net.youthdev.vievie.core.framework.localization

object MessageCode {

  val QUESTION_UPDATE_REQUIRED = "message.question_update_required"
  val DOCTOR_IMPRESSION_NOTIFIED = "message.doctor_impression_notified"
  val HEADER_CONSULTATION_FINISHED = "message.header.consultation_finished"
  val LAB_TEST_BOOKED = "message.lab_test_booked"
  val TITLE_CALL_ENDED = "message.title.call_ended"
  val TITLE_CALL_MISSED = "message.title.call_missed"
  val TITLE_CALL_MISSED_BY_OTHER = "message.title.call_missed_by_other"
  val EVENT_DOCTOR_JOIN_THE_CHAT = "message.event.doctor_join_the_chat"
  val EVENT_TITLE_RESULT_COMMENTED_FOR_PATIENT = "message.event.title.result_commented_for_patient"
  val GREETING = "message.greeting"
  val PROFILE_UPDATE_REQUIRED = "message.profile_update_required"
  val DOCTOR_ASSIGNED = "message.doctor_assigned"
  val HEADER_CONSULTATION_NEED_2ND_OPINION = "message.header.consultation_need_2nd_opinion"
  val HEADER_REFERRAL_REQUEST = "message.header.referral_request"
  val REFERRAL_REQUEST_WAS_SENT = "message.referral_request_was_sent"
  val REFERRAL_REQUEST_ACCEPTED_NOTIFY_FOR_REFERRED_DOCTOR = "message.referral_request_accepted_notify_for_referred_doctor"
  val NURSE_REFERRAL_REQUEST_ACCEPTED_NOTIFY_FOR_REFERRED_DOCTOR = "message.nurse_referral_request_accepted_notify_for_referred_doctor"
  val REFERRAL_REQUEST_ACCEPTED_NOTIFY_FOR_REFERRING_DOCTOR = "message.referral_request_accepted_notify_for_referring_doctor"
  val REFERRAL_REQUEST_DECLINED_NOTIFY_FOR_REFERRING_DOCTOR = "message.referral_request_declined_notify_for_referring_doctor"
  val CONSULTATION_REOPEN = "message.consultation_reopen"
  val LAB_TEST_SUGGESTED_FOR_PATIENT = "message.lab_test_suggested_for_patient"
  val LAB_TEST_SUGGESTED_FOR_DOCTOR = "message.lab_test_suggested_for_doctor"
  val CURRENT_USER = "message.current_user"
  val TITLE_CALL_DECLINED_BY_YOU = "message.title.call_declined_by_you"
  val TITLE_CALL_DECLINED_BY_OTHER = "message.title.call_declined_by_other"
  val EVENT_TITLE_SHARING_REQUEST = "message.event.title.sharing_request"
  val EVENT_TITLE_RESULT_SHARED_FOR_PATIENT = "message.event.title.result_shared_for_patient"
  val EVENT_RESULT_SHARED_FOR_PATIENT = "message.event.result_shared_for_patient"
  val EVENT_TITLE_RESULT_SHARED_FOR_DOCTOR = "message.event.title.result_shared_for_doctor"
  val EVENT_RESULT_SHARED_FOR_DOCTOR = "message.event.result_shared_for_doctor"
  val EVENT_TITLE_PATIENT_RESULT_AVAILABLE = "message.event.title.patient.result_available"
  val PATIENT_LAB_TEST_RESULT_AVAILABLE = "message.patient.lab_test_result_available"
  val EVENT_TITLE_DOCTOR_RESULT_AVAILABLE = "message.event.title.doctor.result_available"
  val DOCTOR_LAB_TEST_RESULT_AVAILABLE = "message.doctor.lab_test_result_available"
  val HEADER_NURSE_REFERRAL_REQUEST = "message.header.nurse_referral_request"
  val NURSE_REFERRAL_REQUEST_WAS_SENT = "message.nurse_referral_request_was_sent"
  val HEADER_NURSE_CANCEL_REFERRAL_REQUEST = "message.header.nurse_referral_request.cancel"
  val NURSE_CANCEL_REFERRAL_REQUEST = "message.nurse_referral_request.cancel"
  val EVENT_RESULT_COMMENTED_FOR_PATIENT = "message.event.result_commented_for_patient"
  val EVENT_RESULT_COMMENTED_FOR_DOCTOR = "message.event.result_commented_for_doctor"
  val EVENT_DOCTOR_JOIN_THE_CHAT_AFTER_REFERRAL = "message.event.doctor_join_the_chat_after_referral"
  val EVENT_DOCTOR_NEED_REFERRAL = "message.event.doctor_need_referral"
  val ACCEPT_REOPEN_REQUEST = "message.accept_reopen_request"

  val CONSULTATION_FINISHED_FOR_DOCTOR = "message.consultation_finished_for_doctor"
  val CONSULTATION_NEED_SECOND_OPINION_FOR_DOCTOR = "message.consultation_need_second_opinion_for_doctor"

  val SMS_SIGNUP_CONFIRM_OTP = "sms.signup_confirm_otp"

  val HEADER_CASE_SNOOZED_WITH_MINUTE_ONLY = "message.header.case.snoozed.with_minute_only"
  val HEADER_CASE_SNOOZED_WITH_HOUR_MINUTE = "message.header.case.snoozed.with_hour_minute"
  val HEADER_CASE_SNOOZED = "message.header.case.snoozed"
}
