package net.youthdev.vievie.infrastructure.token.model

enum class Permission(
    val value: String
) {
  GENERATE_VOUCHER("CORE_SERVICE.VOUCHER_GENERATION.CREATE"),
  EXPORT_VOUCHER_GENERATION_LOG("CORE_SERVICE.VOUCHER_GENERATION.EXPORT"),
  DEBUG_SMS_CODE("DEBUG_SMS_CODE"),
  CREATE_NOTIFICATION("CORE_SERVICE.NOTIFICATION.CREATE"),
  DOWNLOAD_NOTIFICATION_REPORT("CORE_SERVICE.NOTIFICATION.REPORT.DOWNLOAD")
}